name: CI - Shrinx Compression Test

# CI temporarily disabled
# on:
#   push:
#     branches: [main]
#   pull_request:
#     branches: [main]

jobs:
  test-shrinx:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -e .

    - name: Run compression test
      run: |
        python -m shrinx test_sample.json --output test_output.jsonl

    - name: Check compression output
      run: |
        if [ ! -f "test_output.jsonl" ]; then
          echo "Compression failed: Output file not created"
          exit 1
        fi
        echo "Compression test passed"

